name: Publish

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: Setup git
        run: |
          git config user.email "nathan@yellowslicker.com"
          git config user.name "Auto Nathan"

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        # with:
        #   fallback: 0.1.1 # Optional fallback tag to use when no tag can be found

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Release notes
        id: releasenotes
        run: |
          prev={{ steps.previoustag.outputs.tag }}
          notes="$(git log --pretty="### %s%n%b%n%h - %an(%ae) - %ad%n%n" $prev..HEAD)"
          printf "%s" -- "::set-output name=release_notes::$notes)

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.newversion.outputs.v_patch }}
          release_name: ${{ steps.newversion.outputs.v_patch }}
          body_path: ${{ steps.releasenotes.outputs.release_notes }}
          draft: false
          prerelease: false
