name: Publish

on:
  push:
    branches: [ main ]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup git
        run: |
          git config user.email "nathan@yellowslicker.com"
          git config user.name "Auto Nathan"

      - name: Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Minor bump
        id: newversion
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Release notes
        id: releasenotes
        run: |
          prev={{ steps.previoustag.outpus.tag }}
          notes="$(git log --pretty="### %s%n%b%n%h - %an(%ae) - %ad%n%n" $prev..HEAD)"
          printf "%s" -- "::set-output name=release_notes::$notes)

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.newversion.outputs.v_minor }}
          release_name: ${{ steps.newversion.outputs.v_minor }}
          body_path: ${{ steps.releasenotes.outputs.release_notes }}
          draft: false
          prerelease: false
