name: Publish Release

concurrency: release

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Type of release
        options:
          - patch
          - minor
          - major

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: Setup git
        run: |
          git config user.email "nathan@yellowslicker.com"
          git config user.name "Auto Nathan"

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        # with:
        #   fallback: 0.1.1 # Optional fallback tag to use when no tag can be found

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Patch Release
        if: ${{ github.event.inputs.release_type == 'patch'}}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.v_patch }}
          release_name: ${{ steps.semvers.outputs.v_patch }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Create Minor Release
        if: ${{ github.event.inputs.release_type == 'minor'}}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.v_minor }}
          release_name: ${{ steps.semvers.outputs.v_minor }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Create Major Release
        if: ${{ github.event.inputs.release_type == 'major'}}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.v_major }}
          release_name: ${{ steps.semvers.outputs.v_major }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

